export * from './auth.service';
export * from './api.service';
export * from './pictures.service';
export * from './room.service';
export * from './booking.service';
export * from './client.service';
export * from './product.service';
export * from './operator.service';
export * from './bill.service';
